### ISSUE TITLE
Template Design & Code Generator - image don't work

### ISSUE THREAD

**Issue by issimissimo** [hand-dot/labelmake#31]
Hello,
when I create a new field with "image" as type I can't put any image.

**Comment by hand-dot** [comment]
@issimissimo 
具体的なコードをここに貼り付けていただけますか？

**Comment by hand-dot** [comment]
@issimissimo 
Fixed. Can you check it out?

**Comment by issimissimo** [comment]
Hello, I'm testing on this web page:
https://labelmake.jp/javascript-pdf-generator-library/template-design/
but images still don't show

**Comment by hand-dot** [comment]
@issimissimo 
Are you sure? It's showing up on my pc...
<img width="1440" alt="Screen Shot 2021-04-23 at 0 38 12" src="https://user-images.githubusercontent.com/24843808/115743071-474fcc80-a3cc-11eb-8a2a-2ef6a022f64a.png">
